[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    '@anthonymartin/=node_modules/@anthonymartin/',
    '@balancer-labs/=node_modules/@balancer-labs/',
    '@chainlink/=node_modules/@chainlink/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'openzeppelin-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@popcorn/=node_modules/@popcorn/',
    '@setprotocol/=node_modules/@setprotocol/',
    '@uniswap/=node_modules/@uniswap/',
    'base64-sol/=node_modules/base64-sol/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'merkle-tree-solidity/=node_modules/merkle-tree-solidity/',
    'openzeppelin-v3/=node_modules/openzeppelin-v3/',
    'solmate/=node_modules/solmate/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
